pygments: true
permalink: /posts/:title
auto: true
title : Cascading Thoughts
production_url : http://andrerod.github.com
description: ""
disqus_shortname: andrerodblog
tags_path : /tags.html
analytics: UA-40322204-1
author :
  name : Andre Rodrigues
  github : andrerod
  twitter : andremrodrigues
  linkedin: andrerod